### ISSUE TITLE
Upload Service and Login service failing to start

### ISSUE THREAD

**Issue by iarora93** [airavata-courses/CodeNinja502#15]
Hi the above service is not getting started,

Getting the following Error-
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../validation/image'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\ishne\CodeNinja502\project-hub\website\backend\routes\upload.js:5:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\ishne\CodeNinja502\project-hub\website\backend\app.js:17:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

Other 2 services (upload information about posts to MongoDB) and (Run React Frontend) are currently running

**Comment by morparia-p** [comment]
Hey @iarora93,

Thanks for reporting the bug. 
Fixed the patch. Forgot to add a few files to commit. Now it's working.
https://github.com/airavata-courses/CodeNinja502/commit/fa2a0f5bc17898a34f323f581066ffc0f1620b15

Please feel free to report any other issues too.

**Comment by iarora93** [comment]
Looks to be working fine now
